```{r}
library(rvest)
library(tidyverse)
library(timeDate)
library(googlesheets4)
library(markovchain)
```

```{r}
sheet <- "Market Data Backup"
raw_df <- read_sheet("https://docs.google.com/spreadsheets/d/1ig3mbe43WIVZbHNuTI70AYLih4WryOqm6KujYc4bUeM/edit#gid=555070615", sheet=sheet)
df <- data.frame(raw_df[89:252,])
```


```{r}
# Initialize dataframe and program
df <- data.frame()
run <- T

# Initialize NYSE Open/Close Times
holidays <- as.character(holidayNYSE(year = getRmetricsOptions("currentYear")))
market_open <- as.POSIXlt(paste(Sys.Date(),'9:30:00',sep=""))
market_close <- as.POSIXlt(paste(Sys.Date(),'16:00:00',sep=""))
today <- as.character(Sys.Date())

# Initialize Buckets
labels <- c("vhn","hn","ln","lp","hp","vhp")
breaks <- c(-Inf,-2, -1, 0, 1, 2, Inf) 

while(run==T){
  while(! today %in% holidays & isWeekday(today)){
    
    # Retrieve Data
    raw_list <- list()
    for (i in seq(1,10,1)){
      page_number <- i
      main_page <- html_session(paste("https://markets.businessinsider.com/index/s&p_500?p=",i, sep = ""))
      main_page <- read_html(main_page)
      raw_page <- main_page %>% 
        html_nodes("tr.row-hover") %>% 
        html_text()
      raw_list <- append(raw_list, raw_page)
    }
    
    # Clean Data
    clean1 <- sapply(raw_list, str_extract_all, "\r\n.+\t")
    clean2 <- sapply(clean1, str_remove_all, "\r")
    clean3 <- sapply(clean2, str_remove_all, "\t")
    clean4 <- sapply(clean3, str_remove_all, "\n")
    temp_df <- do.call(cbind, clean4)
    temp_df <- as.data.frame(temp_df)
    names(temp_df) <- temp_df %>% slice(1) %>% unlist()
    temp_df <- Filter(function(x)!all(x==""), temp_df)
    temp_df <- temp_df[5,]
    temp_df$time <- as.character(Sys.time())
    df <- rbind(df, temp_df)
    print(head(df))
    
    # Write Data to GoogleSheet
    # sheet_name <- "Market Data Backup"
    # id = as_sheets_id('1ig3mbe43WIVZbHNuTI70AYLih4WryOqm6KujYc4bUeM')
    # id %>% sheet_append(temp_df, sheet=sheet_name)
    
    # Bucket Data
    labelled_df <- df
    for (i in seq(1,length(labelled_df)-1,1)){
      labelled_df[,i] <- str_remove_all(labelled_df[,i], ",")
      labelled_df[,i] <- as.numeric(as.character(labelled_df[,i]))
      labelled_df[,i] <- scale(labelled_df[,i])
      labelled_df[,i] <- cut(labelled_df[,i], breaks=breaks, labels=labels)
    }
    
    # Only use when reading data from googlesheet
    labelled_df$time <- as.POSIXct(labelled_df$time)
    print("Market is open, data is being recorded...")
    print(labelled_df$time)
    Sys.sleep(5)
    closeAllConnections()
    Sys.sleep(55)
  }
  print("Market is closed, trying again in two minutes...")
  Sys.sleep(120)
}
as.character(Sys.Date())
```

```{r}
patterns_df <- data.frame()
for (i in seq(1,length(df$X3M),1)){
  pattern <- df[i,]  
}
```
