---
title: "Untitled"
output: html_document
---




```{r}
library(tidyverse)
library(timeDate)
library(googlesheets4)
library(forecast)
library(xts)
```





```{r setup, include=FALSE}
sheet <- "Market Data Backup"
raw_df <- read_sheet("https://docs.google.com/spreadsheets/d/1ig3mbe43WIVZbHNuTI70AYLih4WryOqm6KujYc4bUeM/edit#gid=555070615", sheet=sheet)
raw_df[,2:length(raw_df)] <- sapply(raw_df[,2:length(raw_df)], str_remove_all, ",")
raw_df[,2:length(raw_df)] <- sapply(raw_df[,2:length(raw_df)], as.numeric)
raw_df <- raw_df[ , colSums(is.na(raw_df)) == 0]
```





```{r}
stockcount <- data.frame()

for(threshold in seq(0, .99, .1)){
  # Initialize list of stock names to keep
  goodstocks <- vector()
  
  for (n in colnames(raw_df[,2:ncol(raw_df)])){
    
    # Filter Stock and Create Differences Column
    df <- raw_df %>% 
      filter(as.Date(time)==Sys.Date()) %>% 
      select(time, n)
    df$Differences <- append(0,diff(unlist(df[,n])))
    df <- df %>% filter(Differences != 0)
    
    #Count Differences > 0
    c <- df %>% 
      filter(Differences > 0)
    
    # Filter Good Stocks
    if( nrow(c) / nrow(df) > threshold ){
      goodstocks <- append(n, goodstocks)
    }
  }
  stockcount <- rbind(stockcount, c(threshold, length(goodstocks)))
}

colnames(stockcount) <- c("threshold", "count")
```
