---
title: "Untitled"
output: html_document
---

```{r}
library(rvest)
library(tidyverse)
library(timeDate)
library(googlesheets4)
library(e1071)
```

```{r setup, include=FALSE}
sheet <- "Market Data Backup"
raw_df <- read_sheet("https://docs.google.com/spreadsheets/d/1ig3mbe43WIVZbHNuTI70AYLih4WryOqm6KujYc4bUeM/edit#gid=555070615", sheet=sheet)
raw_df[,2:length(raw_df)] <- sapply(raw_df[,2:length(raw_df)], str_remove_all, ",")
raw_df[,2:length(raw_df)] <- sapply(raw_df[,2:length(raw_df)], as.numeric)
```

```{r}
months <- 1:nrow(raw_df)
DF <- data.frame(months,raw_df$`Activision Blizzard`)
colnames(DF)<-c("x","y")
svmodel <- svm(y ~ x,data=DF, type="eps-regression",kernel="radial",cost=100, gamma=5)

nd <- 1:nrow(raw_df)+1

prognoza <- predict(svmodel, newdata=data.frame(x=nd), interval = "prediction")

#plot the results
ylim <- c(min(DF$y), max(DF$y))
xlim <- c(min(nd),max(nd))
plot(DF$y, col="blue", ylim=ylim, xlim=xlim, type="l")
par(new=TRUE)
plot(prognoza, col="red", ylim=ylim, xlim=xlim)
```
